FROM osrf/ros:humble-desktop

# Gazebo Garden Install
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y lsb-release wget gnupg curl nano

RUN apt-get update
RUN wget https://packages.osrfoundation.org/gazebo.gpg -O /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null
RUN apt-get update
RUN apt-get install -y gz-garden

CMD [ "/bin/bash" ]